---
- name: Tap external Homebrew repositories
  homebrew_tap:
    name: "{{ homebrew_repositories }}"
    state: present
  when:
    - "homebrew_repositories|bool"

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install/Upgrade Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: latest
  loop: "{{ homebrew_packages }}"

