---
- name: Tap external Homebrew repositories
  homebrew_tap:
    name: "{{ homebrew_repositories }}"
    state: latest

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install/Upgrade Homebrew packages
  homebrew:
    name: "{{ homebrew_packages }}"
    state: latest

